# Generated by Django 3.2.3 on 2021-05-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
