# Generated by Django 3.2.3 on 2021-05-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('updated_at', models.TimeField()),
            ],
        ),
    ]
