# Generated by Django 3.2.3 on 2021-05-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210518_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='streamers',
            field=models.ManyToManyField(related_name='games', to='app.Streamer'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='url',
            field=models.URLField(),
        ),
    ]
